name: egy_tour
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
  smooth_page_indicator: ^1.2.1
  dio: ^5.8.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  font_awesome_flutter: ^10.8.0
  dartz: ^0.10.1
  awesome_snackbar_content:
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  auto_size_text: ^3.0.0
  geolocator: ^13.0.2
  animated_text_kit: ^4.2.3
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  geocode: ^1.0.3
  permission_handler:
  flutter_advanced_switch: ^3.1.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  icon_broken: ^1.1.0
  flutter_screenutil: ^5.9.3
  curved_labeled_navigation_bar: ^2.0.6
  image_picker: ^0.8.7+3
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  supabase_flutter: ^2.8.4
  fluttertoast: ^8.2.12
  firebase_messaging: ^15.2.5
  flutter_portal: ^1.1.4
  readmore: ^3.0.0
  url_launcher: ^6.1.11


dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/fonts/Ubuntu/
    - assets/fonts/Quicksand/
    - assets/fonts/Quicksand/static/
    - assets/
    - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/static/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand/static/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand/static/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/static/Quicksand-Bold.ttf
          weight: 700
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf

flutter_icons:
  android: true
  ios: true
  windows:
    generate: true
  macos:
    generate: true
  linux:
    generate: true
  web:
    generate: true
  image_path: "assets/images/ic_launcher.png"
