// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDQJMy2h4XUg3Ah7JWZcR2fAcwMeEKn3I',
    appId: '1:813815578962:web:fe8ae28616e6c9b6ceba8b',
    messagingSenderId: '813815578962',
    projectId: 'egy-tour-6f55f',
    authDomain: 'egy-tour-6f55f.firebaseapp.com',
    storageBucket: 'egy-tour-6f55f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYdZk6yBcsg4T7BcKrfoiNSXu9mFH0iD0',
    appId: '1:813815578962:android:216e6c0849653feeceba8b',
    messagingSenderId: '813815578962',
    projectId: 'egy-tour-6f55f',
    storageBucket: 'egy-tour-6f55f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBndV8T0ybw9Dn5ISfoCjqNRwu6Mxx3A6U',
    appId: '1:813815578962:ios:62e2be0db3b62d7aceba8b',
    messagingSenderId: '813815578962',
    projectId: 'egy-tour-6f55f',
    storageBucket: 'egy-tour-6f55f.firebasestorage.app',
    iosBundleId: 'com.example.egyTour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBndV8T0ybw9Dn5ISfoCjqNRwu6Mxx3A6U',
    appId: '1:813815578962:ios:62e2be0db3b62d7aceba8b',
    messagingSenderId: '813815578962',
    projectId: 'egy-tour-6f55f',
    storageBucket: 'egy-tour-6f55f.firebasestorage.app',
    iosBundleId: 'com.example.egyTour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDQJMy2h4XUg3Ah7JWZcR2fAcwMeEKn3I',
    appId: '1:813815578962:web:d66a34cb6125aedaceba8b',
    messagingSenderId: '813815578962',
    projectId: 'egy-tour-6f55f',
    authDomain: 'egy-tour-6f55f.firebaseapp.com',
    storageBucket: 'egy-tour-6f55f.firebasestorage.app',
  );

}